# Generated by Django 2.2.6 on 2019-12-03 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0008_auto_20191127_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('game_time_limit', models.PositiveIntegerField(default=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.PositiveIntegerField(default=10)),
                ('is_only_sub_members', models.BooleanField(default=False)),
                ('is_entry_before_tournament', models.BooleanField(default=True)),
                ('is_entry_after_half_time', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayerManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(related_name='tp_players', through='tournament.TournamentPlayerManager', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tp_tournament', to='tournament.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournamentplayermanager',
            name='tournament_players',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_tp', to='tournament.TournamentPlayers'),
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=30)),
                ('room_id', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'waiting'), ('2', 'started'), ('3', 'declined'), ('4', 'timedout'), ('5', 'finished')], default='1', max_length=20)),
                ('game_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_game_type', to='game.GameType')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_player2', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_tournament', to='tournament.Tournament')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
