# Generated by Django 2.2.6 on 2019-12-04 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0008_auto_20191127_1132'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentGameManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=30)),
                ('room_id', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'waiting'), ('2', 'started'), ('3', 'declined'), ('4', 'timedout'), ('5', 'finished')], default='1', max_length=20)),
                ('winning_streak', models.CharField(blank=True, max_length=100, null=True)),
                ('game_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_game_type', to='game.GameType')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_player2', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_tournament', to='tournament.Tournament')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tournamentplayers',
            name='players',
        ),
        migrations.RemoveField(
            model_name='tournamentplayers',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentplayermanager',
            name='tournament_players',
        ),
        migrations.AddField(
            model_name='tournamentplayermanager',
            name='total_games_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentplayermanager',
            name='total_games_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentplayermanager',
            name='total_games_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentplayermanager',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpm_tp', to='tournament.Tournament'),
        ),
        migrations.DeleteModel(
            name='TournamentGame',
        ),
        migrations.DeleteModel(
            name='TournamentPlayers',
        ),
    ]
