# Generated by Django 2.2.6 on 2020-05-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20200107_1013'),
        ('tournament', '0002_auto_20191204_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentgamemanager',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='tournamentgamemanager',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tournamentgamemanager',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='tournamentgamemanager',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='tournamentgamemanager',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='tournamentgamemanager',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='tournamentgamemanager',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tournamentgamemanager',
            name='winner',
        ),
        migrations.AddField(
            model_name='tournamentgamemanager',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tg_game', to='game.Game'),
        ),
    ]
