# Generated by Django 2.2.6 on 2020-05-15 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20200514_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
