# Generated by Django 2.2.6 on 2020-05-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20200515_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayermanager',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
