# Generated by Django 2.2.6 on 2019-10-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_country',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
