# Generated by Django 2.2.6 on 2019-10-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_author_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_on',
            new_name='actually_created_on',
        ),
    ]
