# Generated by Django 2.2.6 on 2019-10-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191029_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_on',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
