# Generated by Django 2.2.6 on 2019-10-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_file',
            field=models.FileField(max_length=9000, upload_to='articles'),
        ),
    ]
