# Generated by Django 2.2.6 on 2019-10-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191030_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_profile_photo',
            field=models.ImageField(default='', max_length=9000, upload_to='articles'),
        ),
    ]
