# Generated by Django 2.2.6 on 2019-10-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_file_url',
            field=models.URLField(blank=True, default='', max_length=9000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='author_profile_photo_url',
            field=models.URLField(blank=True, default='', max_length=9000, null=True),
        ),
    ]
