# Generated by Django 2.2.6 on 2019-10-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20191031_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='article',
            name='preview_image_url',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_profile_photo',
            field=models.ImageField(blank=True, default='', max_length=9000, null=True, upload_to='articles'),
        ),
    ]
