# Generated by Django 2.2.6 on 2019-11-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_videowatchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
