# Generated by Django 2.2.6 on 2019-11-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_video_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='authorpicurl',
            field=models.URLField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
