# Generated by Django 2.2.6 on 2019-11-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_video_authorpicurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocategory',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
