# Generated by Django 2.2.6 on 2019-11-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20191114_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocategory',
            name='is_temp',
            field=models.BooleanField(default=True),
        ),
    ]
