# Generated by Django 2.2.6 on 2019-11-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_remove_videocategory_is_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocategory',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
