# Generated by Django 2.2.6 on 2019-11-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycode',
            name='count_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
