# Generated by Django 2.2.6 on 2019-11-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_countrycode_count_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskilllevels',
            name='total_point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
