# Generated by Django 2.2.6 on 2019-12-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usernotification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='req_type',
            field=models.CharField(choices=[('1', 'friend request'), ('2', 'game request')], default='1', max_length=50),
        ),
    ]
