# Generated by Django 2.2.6 on 2019-12-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usernotification_req_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='ref_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
