# Generated by Django 2.2.6 on 2019-12-27 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usernotification_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('max_users', models.PositiveIntegerField(default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(related_name='ngusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
