# Generated by Django 2.2.6 on 2020-05-09 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
