# Generated by Django 2.2.6 on 2020-06-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_playerpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='req_type',
            field=models.CharField(choices=[('1', 'friend request'), ('2', 'game request'), ('3', 'from admin'), ('4', 'new chat'), ('5', 'new message'), ('6', 'new article'), ('7', 'new achievement'), ('8', 'new tournament'), ('9', 'new rank'), ('10', 'tournament winner'), ('11', 'subscription')], default='1', max_length=50),
        ),
    ]
