# Generated by Django 2.2.6 on 2019-10-24 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, choices=[('1', 'Yearly'), ('2', 'Monthly')], max_length=50, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlanBenifits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benifit', models.CharField(blank=True, max_length=200, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benifits_plan', to='usubscription.SubscriptionPlan')),
            ],
        ),
    ]
