# Generated by Django 2.2.6 on 2020-02-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usubscription', '0002_auto_20200210_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='period',
            new_name='period_m',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='price',
            new_name='price_m',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='period_y',
            field=models.CharField(blank=True, choices=[('1', 'Yearly'), ('2', 'Monthly')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_y',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
