# Generated by Django 2.2.6 on 2020-02-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usubscription', '0003_auto_20200210_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_m',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_y',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
