# Generated by Django 2.2.6 on 2020-03-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usubscription', '0004_auto_20200210_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='period_m',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='period_y',
        ),
    ]
