# Generated by Django 2.2.6 on 2020-05-12 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usubscription', '0005_auto_20200325_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Credit Card', '1'), ('Debit Card', '2'), ('Netbanking', '3'), ('Paypal', '4'), ('Terl', '5')], max_length=10)),
                ('status', models.CharField(choices=[('Completed', '1'), ('Declined', '2'), ('Cancelled', '3'), ('Pending', '4')], max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_pay', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splan_pay', to='usubscription.SubscriptionPlan')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_tran', to='usubscription.Transaction')),
            ],
        ),
    ]
