FROM ubuntu:18.04
MAINTAINER sukamal
RUN    apt-get update -y
RUN    apt-get install software-properties-common -y
RUN    add-apt-repository ppa:deadsnakes/ppa -y
RUN    apt-get install python3.7 -y
RUN    apt install python3-pip -y
COPY . /chess
WORKDIR /chess
RUN    pip3 install -r requirements.txt
RUN    pip3 install psycopg2-binary
ENTRYPOINT ["python3"]
CMD ["app.py"]
