# Generated by Django 2.2.6 on 2019-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
