# Generated by Django 2.2.6 on 2019-11-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191126_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
