# Generated by Django 2.2.6 on 2019-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='room_id',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
