# Generated by Django 2.2.6 on 2019-11-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('1', 'waiting'), ('2', 'started'), ('3', 'declined'), ('4', 'timedout'), ('5', 'finished')], default='1', max_length=20),
        ),
    ]
