# Generated by Django 2.2.6 on 2019-12-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20191127_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='request_status',
            field=models.CharField(choices=[('1', 'waiting'), ('2', 'accepted'), ('3', 'declined')], default='1', max_length=50),
        ),
    ]
