# Generated by Django 2.2.6 on 2019-12-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_friends_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='request_status',
        ),
    ]
