# Generated by Django 2.2.6 on 2019-12-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_friends_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='status',
            field=models.CharField(choices=[('1', 'waiting'), ('2', 'accepted'), ('3', 'declined')], default='1', max_length=50),
        ),
    ]
