# Generated by Django 2.2.6 on 2019-12-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20191217_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleImageStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_image', models.ImageField(blank=True, null=True, upload_to='user/profile_image')),
            ],
        ),
    ]
