# Generated by Django 2.2.6 on 2019-12-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_sampleimagestore_unique_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleimagestore',
            name='sample_data',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
