# Generated by Django 2.2.6 on 2020-05-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20200107_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
