# Generated by Django 2.2.6 on 2020-02-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
