# Generated by Django 2.2.6 on 2020-05-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_auto_20200206_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementmanager',
            name='created_on',
            field=models.DateTimeField(default=None),
        ),
    ]
