# Generated by Django 2.2.6 on 2020-05-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_achievementmanager_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementmanager',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
