# Generated by Django 2.2.6 on 2020-05-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0004_auto_20200509_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementmanager',
            old_name='user',
            new_name='player',
        ),
    ]
