# Generated by Django 2.2.6 on 2020-05-07 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='puzzles/category')),
                ('iconurl', models.URLField(blank=True, default='', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('video', models.FileField(blank=True, null=True, upload_to='puzzles/videos')),
                ('videourl', models.URLField(blank=True, default='', null=True)),
                ('videopreview', models.ImageField(blank=True, null=True, upload_to='puzzles/videoprevs')),
                ('videopreviewurl', models.URLField(blank=True, default='', null=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('hint', models.CharField(default='', max_length=1000)),
                ('explanation', models.CharField(default='', max_length=1000)),
                ('learned', models.CharField(default='', max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_cat', to='puzzles.PuzzleCategory')),
            ],
        ),
    ]
