# Generated by Django 2.2.6 on 2020-01-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='lessons/category')),
                ('iconurl', models.URLField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('video', models.FileField(blank=True, null=True, upload_to='lessons/videos')),
                ('videourl', models.URLField(default='')),
                ('videopreview', models.ImageField(blank=True, null=True, upload_to='lessons/videoprevs')),
                ('videopreviewurl', models.URLField(default='')),
                ('description', models.CharField(default='', max_length=1000)),
                ('hint', models.CharField(default='', max_length=1000)),
                ('explanation', models.CharField(default='', max_length=1000)),
                ('learned', models.CharField(default='', max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_cat', to='lessons.LessonCategory')),
            ],
        ),
    ]
