# Generated by Django 2.2.6 on 2020-01-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20200103_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessoncategory',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
