# Generated by Django 2.2.6 on 2020-05-09 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0004_tactic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lm_lesson', to='lessons.Lesson')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lm_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
