# Generated by Django 2.2.6 on 2020-05-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessonmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='lessons/images'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
