# Generated by Django 2.2.6 on 2020-05-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20200519_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_image_url',
        ),
    ]
