# Generated by Django 2.2.6 on 2020-05-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20200525_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_image_url',
        ),
    ]
